name: PR Tests

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史用于SonarQube分析

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black bandit safety

    - name: Lint Python code
      working-directory: ./python
      run: |
        flake8 agentbay tests examples
        black --check agentbay tests examples

    - name: Security scan with Bandit
      working-directory: ./python
      run: |
        bandit -r agentbay -f json -o bandit-results.json

    - name: Check dependencies for vulnerabilities
      working-directory: ./python
      run: |
        poetry export -f requirements.txt -o requirements.txt --without-hashes
        safety check -r requirements.txt || true

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ./python
        args: >
          -Dsonar.projectKey=wuying-agentbay-sdk_python
          -Dsonar.organization=wuying-agentbay
          -Dsonar.python.coverage.reportPaths=coverage.xml

  python-tests:
    needs: lint
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit

  quality-gate:
    needs: [python-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check Codecov coverage threshold
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "70"
          filename: "./python/coverage.xml"
          clover: true
          log-level: error
